# Generated by Django 5.2.4 on 2026-03-03 05:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches_branch_name', models.CharField(max_length=30, unique=True)),
                ('branches_branch_code', models.CharField(max_length=3, unique=True)),
                ('branches_rollno_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_cate_category_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_quantity_available', models.PositiveIntegerField(default=0)),
                ('comp_popularity', models.PositiveIntegerField(default=0)),
                ('comp_status', models.BooleanField(default=True)),
                ('comp_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components_inthis_category', to='final.componentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties_inthis_dept', to='final.branches')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_proj_project_name', models.CharField(max_length=100)),
                ('avail_proj_faculty_associated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_ofthis_faculty', to='final.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only letters allowed (2–30 characters)', regex='^[A-Za-z]{2,30}$')])),
                ('std_last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only letters allowed (2–30 characters)', regex='^[A-Za-z]{2,30}$')])),
                ('std_year', models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')])),
                ('std_roll_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be exactly 10 digits', regex='^[2-9][0-9]ESK[a-zA-Z]{2}[0-9]{3}$')])),
                ('std_college_email', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Use your official college email', regex='^[b][2-9][0-9]{5}')])),
                ('std_phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian mobile number', regex='^[6-9][0-9]{9}$')])),
                ('std_password', models.CharField(max_length=128)),
                ('std_joined_at', models.DateField(auto_now_add=True, db_index=True)),
                ('std_deactivated_at', models.DateField(blank=True, null=True)),
                ('std_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students_inthis_branch', to='final.branches')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEnrolledStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_enroll_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='final.availableprojects')),
                ('proj_enroll_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_enrolled', to='final.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_issue_quantity_issued', models.PositiveIntegerField()),
                ('std_issue_form_date', models.DateField(blank=True)),
                ('std_issue_issue_date', models.DateField(blank=True, db_index=True, null=True)),
                ('std_issue_return_date', models.DateField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_issue_logs', to='final.component')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_info', to='final.availableprojects')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='std_issue_logs', to='final.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['std_branch', 'std_year'], name='final_stude_std_bra_d42d45_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_roll_number__regex', '^[2-9][0-9]ESK[a-zA-Z]{2}[0-9]{3}$')), name='roll_number_10_digits'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_phone_number__regex', '^[6-9][0-9]{9}$')), name='phone_number_india'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_college_email__regex', '^[b][2-9][0-9]{5}$')), name='college_email_domain'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_first_name', models.F('std_last_name')), _negated=True), name='first_last_name_not_same'),
        ),
    ]
