# Generated by Django 5.2.4 on 2026-02-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_deactivated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentissuelog',
            name='std_issue_form_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentissuelog',
            name='std_issue_issue_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentissuelog',
            name='std_issue_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
