# Generated by Django 5.2.4 on 2026-07-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='comp_popularity',
        ),
        migrations.DeleteModel(
            name='ProjectEnrolledStudents',
        ),
    ]
