# Generated by Django 5.2.4 on 2026-07-21 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_remove_component_comp_popularity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='roll_number_10_digits',
        ),
        migrations.AlterField(
            model_name='student',
            name='std_roll_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be exactly 10 digits', regex='^[2-9][0-9][eE][sS][kK][a-zA-Z]{2}[0-9]{3}$')]),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('std_roll_number__regex', '^[2-9][0-9][eE][sS][kK][a-zA-Z]{2}[0-9]{3}$')), name='roll_number_10_digits'),
        ),
    ]
