from django.db import models
from django.contrib.auth.hashers import make_password, check_password
from django.core.validators import RegexValidator

#for complex queries like ""OR, NOT"""  in django ORM
from django.db.models import Q

# ---------- Validators ----------
name_validator = RegexValidator(
    regex=r'^[A-Za-z]{2,30}$',
    message="Only letters allowed (2–30 characters)"
)

roll_validator = RegexValidator(
    regex=r'^[2-9][0-9]ESK[a-zA-Z]{2}[0-9]{3}$',
    message="Roll number must be exactly 10 digits"
)

phone_validator = RegexValidator(
    regex=r'^[6-9][0-9]{9}$',
    message="Enter a valid Indian mobile number"
)

college_email_validator = RegexValidator(
    regex=r'^[b][2-9][0-9]{5}',         #not storing @skit.ac.in
    message="Use your official college email"
)
# ------------------------------------------------------------


class ComponentCategory(models.Model):
    comp_cate_category_name = models.CharField(max_length=30,unique=True,null=False)

    def __str__(self):
        return f"{self.comp_cate_category_name}"



class Branches(models.Model):
    #creating unique also creates db_index
    # blank =True/False is for django forms -- --  we have not used
    branches_branch_name =models.CharField(max_length=30,unique=True,null=False)
    branches_branch_code =models.CharField(max_length=3,unique=True,null=False)
    branches_rollno_code = models.CharField(max_length=3,unique=True,null=False)

    def __str__(self):
        return f"{self.branches_branch_code}"



class Faculty(models.Model):
    faculty_name = models.CharField(max_length=100,null=False)   #don't keep unique

    faculty_dept = models.ForeignKey(
        Branches,
        null=True,
        on_delete=models.SET_NULL,           #we can afford to set dept. null in case branch deletes
        related_name='faculties_inthis_dept')
    # Foreign keys are already indexed in PostgresSQL *** Don't add extra `db_index` ***
    # that is to REMOVE THE INDEX from f. k. if write heavy table


#   ==================================
#     EDIT HEAVY TABLE (but not change comp_id anytime )
#   ==================================
class Component(models.Model):
    #every component will be uniquely identified by primary key id ==>> auto generated by Django
    # Don't make composite keys as componentns will be less in number
    comp_name = models.CharField(max_length=100,null=False)
    comp_quantity_available = models.PositiveIntegerField(default=0,null=False)
    comp_category = models.ForeignKey(
        ComponentCategory,
        on_delete=models.PROTECT,                #componnentcategory can't be deleted until you settle all components in that categry
        related_name="components_inthis_category")

    comp_popularity = models.PositiveIntegerField(default=0)
    comp_status = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.comp_name}"




#   ==================================
#     Mostly append only tables: but becomes `edit` also when changing student entry
#   ==================================
class Student(models.Model):
    YEAR_CHOICES = [
        (1, "1st"),
        (2, "2nd"),
        (3, "3rd"),
        (4, "4th"),
        (5, "5th"),
    ]

    std_id = models.BigAutoField(primary_key=True)

    std_first_name = models.CharField(max_length=30,null=False,validators=[name_validator])
    std_last_name = models.CharField(max_length=30,null=False,validators=[name_validator])

    std_branch=models.ForeignKey(
        Branches,
        on_delete=models.PROTECT,         # Branch can't be deleted until it settle all students in that branch
        related_name="students_inthis_branch"
    )
    std_year=models.PositiveSmallIntegerField(choices=YEAR_CHOICES,null=False)

    std_roll_number = models.CharField(max_length=10,null=False,unique=True, validators=[
        roll_validator])
    std_college_email = models.CharField(max_length=7,null=False,unique=True,validators=[
        college_email_validator])

    std_phone_number = models.CharField(max_length=10,unique=True, null=False,validators=[
        phone_validator])

    std_password = models.CharField(max_length=128,null=False)

# individual index and filter only by a `RANGE OF TIME` not by specific month of joining as then
    # it will scan full table and index is of no use
    std_joined_at = models.DateField(auto_now_add=True,null=False,db_index=True)

    #don;t remove this blank=True as we did full_clean on student now it will run validations and
    # raise Validationerror
    std_deactivated_at = models.DateField(null=True,blank=True)


    def set_password(self, raw_password):
        self.std_password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.std_password)

    @property
    def std_full_name(self):
        return f"{self.std_first_name} {self.std_last_name}"

# Defining explicitly to run validations before saving into students table
    def save(self, *args, **kwargs):
        self.full_clean()                           # 🚨 forces validation on save
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.std_full_name} ({self.std_roll_number}) "


    class Meta:
        indexes = [
            models.Index(fields=[ "std_branch","std_year",]),
        ]

        constraints = [
            models.CheckConstraint(
                check=Q(std_roll_number__regex=r'^[2-9][0-9]ESK[a-zA-Z]{2}[0-9]{3}$'),
                name="roll_number_10_digits"
            ),

            models.CheckConstraint(
                check=Q(std_phone_number__regex=r'^[6-9][0-9]{9}$'),
                name="phone_number_india"
            ),

            models.CheckConstraint(
                check=Q(std_college_email__regex=r'^[b][2-9][0-9]{5}$'),
                name="college_email_domain"
            ),

            # First and last name not same (already stored in lowercase)
            models.CheckConstraint(
                check=~Q(std_first_name=models.F('std_last_name')),
                name="first_last_name_not_same"
            ),

        ]



class AvailableProjects(models.Model):
    avail_proj_project_name = models.CharField(max_length=100,null=False)
    avail_proj_faculty_associated = models.ForeignKey(
        Faculty,
        null=True,
        on_delete=models.SET_NULL,                    # if Faculty gets deleted we can change the null to a new Faculty later
        related_name='projects_ofthis_faculty')

    def __str__(self):
        return f"{self.avail_proj_project_name}"



class ProjectEnrolledStudents(models.Model):
    #one project can have many students : and vice versa
    proj_enroll_project = models.ForeignKey(
        AvailableProjects,
        on_delete=models.PROTECT,
        related_name="enrolled_students"   # all students for this project
    )

    proj_enroll_student = models.ForeignKey(
        Student,
        on_delete=models.PROTECT,
        related_name="projects_enrolled"  # all projects this student is enrolled in
    )


#   ==================================
#     write heavy table
#   ==================================
class StudentIssueLog(models.Model):
    student = models.ForeignKey(
        Student,
        on_delete=models.PROTECT,
        related_name="std_issue_logs",
    )
    component = models.ForeignKey(
        Component,
        on_delete=models.PROTECT,
        related_name="comp_issue_logs"
    )

    project = models.ForeignKey(
        AvailableProjects,
        on_delete=models.PROTECT,
        related_name="project_info")

    std_issue_quantity_issued = models.PositiveIntegerField(null=False)

    #this can't be false as how can it be an entry in the log table
    std_issue_form_date = models.DateField(null=False,blank=True)

    #index only this field as filter main on issue date
    std_issue_issue_date = models.DateField(null=True,db_index=True,blank=True)

    std_issue_return_date = models.DateField(null=True,blank=True)

# This (ForeignKey Reference Error ) will get resolved at runtime. No Problem
    def __str__(self):
        return f"{self.student.std_full_name}->{self.component.comp_name}"




