#Below are Django comments Keep them Don't delete it
"""
Django settings for teststudy project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Database( see line 150)
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Password validation (see line 170)
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Internationalization(see line 186)
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Static files (CSS, JavaScript, Images) (see last of file)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type (see last of file)
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

"""

# ***NOTE*** : Refer 'dependencies' section in readme file
# ========================
# Standard Library
# ========================
import os
from pathlib import Path

# ========================
# Third-Party Libraries
# ========================
import dj_database_url
from dotenv import load_dotenv
from decouple import config                 #This loads at runtime if any variable is causing an issue it's OK.
#-----------------------------------------------------


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / "config" / ".env")


# ------------------
# ***  SECRETS  ***
# ------------------
SECRET_KEY = config('SECRET_KEY')


ADMIN_PATH = os.getenv("ADMIN_PATH")


DEBUG = config('DEBUG', cast=bool)

RENDER_APP_URL = os.getenv('RENDER_APP_URL')


ALLOWED_HOSTS=os.getenv("ALLOWED_HOSTS", "").split(",")


CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "")

# Convert to list if not empty
if CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS.split(",")
else:
    CSRF_TRUSTED_ORIGINS = []


# --------------------
# for mail only TESTING
# --------------------
MAIL_API_KEY = os.environ.get("MAIL_API_KEY")

DEFAULT_FROM_EMAIL = "smtp-relay.brevo.com"
EMAIL_SENDER_NAME = "Inventory System"


# --------------------
# Session cookies
# --------------------
SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE = config('DEBUG', cast=bool)


"""Changed this for the bot signup process"""
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', 1800))
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# --------------------
# CSRF cookie
# --------------------
# CSRF_COOKIE_SECURE =config('DEBUG', cast=bool)

"""Changed this for the bot signup process"""
CSRF_COOKIE_SECURE =False
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'


# --------------------
# HTTPS / proxy settings
# --------------------
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG


# --------------------
# Security headers
# --------------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# ----------------------------------------------


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'final.apps.FinalConfig',
    'simulation.apps.SimulationConfig',

]


# ****  ORDER OF MIDDLEWARE MATTERS   ****
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'teststudy.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'final/templates',

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'teststudy.wsgi.application'


# These are not used as wrapper alread have redirect() but ......  use them as safety net
LOGIN_URL = 'final:login'
LOGIN_REDIRECT_URL = 'final:student_dashboard'
LOGOUT_REDIRECT_URL = 'final:login'



DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL:
    raise ValueError("DATABASE_URL environment variable not set")

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=60)
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# ----- is use LocalMemCache then it is not shared across servers -----
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#     }
# }

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'


#static Files for local
STATICFILES_DIRS = [
    'final/static',
                    ]


#static files for Production
STATIC_ROOT = BASE_DIR / 'staticfilesforproduction'


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
